management.endpoint.health.group.operations.include=outbox
management.endpoint.health.group.operations.show-components=always
management.endpoint.health.group.operations.show-details=always
management.endpoint.health.status.order=down,out-of-service,degraded,unknown,up
management.endpoint.health.status.http-mapping.degraded=200
