version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - automated-maintenance
    commit-message:
      prefix: deps
    groups:
      kotlin-test-libraries:
        patterns:
          - "io.kotest:*"
          - "org.junit*:*"
          - "org.mockito*:*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "02:30"
      timezone: Asia/Shanghai
    labels:
      - dependencies
      - automated-maintenance
    commit-message:
      prefix: ci
