apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jstore
resources:
  - namespace.yaml
  - service-account.yaml
  - runtime-config.yaml
  - artifact-pvc.yaml
  - redis.yaml
  - application.yaml
  - service-monitor.yaml
  - grafana-dashboard.yaml
  - network-policies.yaml
