server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/develop_local?currentSchema=order
spring.datasource.username=develop_local
spring.datasource.password=Jupeter104741

spring.datasource.hikari.pool-name=j-store-order
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=20

spring.jpa.open-in-view = true
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.root=info