[versions]
guava = "33.3.1-jre"
springBoot = "3.3.5"
spring-dependency-management = '1.1.6'
postgresql = "42.7.4"
kotlin-jvm = "1.9.20"
kotlin = "1.9.0"
slf4j = "2.0.16"

[libraries]
guava = {module = "com.google.guava:guava", version.ref = "guava"}
spirng-boot-boot = {module= "org.springframework.boot:spring-boot", version.ref = "springBoot"}
spring-boot-starter-data-jpa = {module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot"}
spring-boot-starter-web = {module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot"}
spring-data-jpa = {module = "org.springframework.data:spring-data-jpa", version.ref = "springBoot"}
spring-data-commons = {module = "org.springframework.data:spring-data-commons", version.ref = "springBoot"}
postgresql = {module = "org.postgresql:postgresql", version.ref = "postgresql"}
spring-boot-configuration-processor = {module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot"}
slf4j-api = {module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
kotlin-stdlib = {module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin"}
kotlin-reflect = {module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin"}



[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
springframework = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }