[versions]
guava = "33.3.1-jre"
springBoot = "3.4.1"
spring-dependency-management = '1.1.7'
postgresql = "42.7.4"
kotlin-jvm = "1.9.20"
kotlin = "1.9.0"
slf4j = "2.0.16"
jackson = "2.18.2"
fastexcel = "1.0.0"
junit = "1.11.4"
transaction-api = "2.0.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
spirng-boot-boot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "springBoot" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons", version.ref = "springBoot" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
fastexcel = { module = "cn.idev.excel:fastexcel", version.ref = "fastexcel" }
transaction-api = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "transaction-api" }





[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
springframework = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }