[versions]
guava = "33.3.1-jre"
springBoot = "3.3.5"

[libraries]
guava = {module = "com.google.guava:guava", version.ref = "guava"}
spring-boot-starter-data-jpa = {module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot"}


[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.20" }