server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/develop?currentSchema=develop
spring.datasource.username=develop
spring.datasource.password=Jupeter104741

spring.datasource.hikari.pool-name=j-store-goods
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=20

spring.jpa.open-in-view = true
spring.jpa.hibernate.ddl-auto=create-drop

spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.group=j-store

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=public
spring.cloud.nacos.config.group=${spring.cloud.nacos.discovery.group}
spring.config.import[0] = nacos:${spring.application.name}?refreshEnabled=true?



logging.level.root=info