apiVersion: apps/v1
kind: Deployment
metadata:
  name: j-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        jstore.logs/environment: development
