apiVersion: v1
kind: ConfigMap
metadata:
  name: jstore-deployment
data:
  JSTORE_DEPLOYMENT_ENVIRONMENT: development
  JSTORE_TRACING_SAMPLING_PROBABILITY: "1.0"
  SPRING_PROFILES_ACTIVE: local,observability,outbox-observability
