apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony
  namespace: agentic-cicd
spec:
  template:
    spec:
      containers:
        - name: symphony
          env:
            - name: JSTORE_SYMPHONY_GITHUB_TOKEN
              value: null
              valueFrom:
                secretKeyRef:
                  name: symphony-github-token
                  key: token
                  optional: false
            - name: JSTORE_GITHUB_TOKEN_EXPIRES_AT_EPOCH_SECONDS
              valueFrom:
                secretKeyRef:
                  name: symphony-github-token
                  key: expires-at-epoch-seconds
                  optional: false
