apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-policy.yaml
  - service-accounts.yaml
  - dispatcher-rbac.yaml
  - network-policies.yaml
  - control-plane.yaml
