apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jstore-observability
resources:
  - namespace.yaml
  - rbac.yaml
  - alloy-config.yaml
  - alloy.yaml
  - loki-config.yaml
  - loki.yaml
  - loki-gateway.yaml
  - prometheus-config.yaml
  - prometheus-alerts.yaml
  - prometheus.yaml
  - grafana-config.yaml
  - grafana.yaml
  - network-policies.yaml
