CREATE TABLE carts (
    id bigint PRIMARY KEY,
    buyer_id bigint NOT NULL,
    status varchar(16) NOT NULL CHECK (status IN ('ACTIVE','EXPIRED')),
    market varchar(32) NOT NULL,
    channel_id varchar(64) NOT NULL,
    currency varchar(3) NOT NULL,
    content_version bigint NOT NULL,
    persistence_version bigint NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_carts_active_buyer ON carts(buyer_id) WHERE status = 'ACTIVE';

CREATE TABLE cart_lines (
    id bigint PRIMARY KEY,
    cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    sku_id bigint NOT NULL,
    offer_id bigint NOT NULL,
    merchant_id bigint NOT NULL,
    quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 999),
    selected boolean NOT NULL,
    added_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    UNIQUE(cart_id, offer_id)
);

CREATE TABLE cart_assessments (
    id bigint PRIMARY KEY,
    cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    source_cart_version bigint NOT NULL,
    status varchar(16) NOT NULL CHECK (status IN ('COMPLETE','PARTIAL','EMPTY')),
    amount_fen bigint NOT NULL CHECK (amount_fen >= 0),
    currency varchar(3) NOT NULL,
    evaluated_at timestamp with time zone NOT NULL,
    UNIQUE(cart_id, source_cart_version)
);

CREATE TABLE cart_assessment_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id bigint NOT NULL REFERENCES cart_assessments(id) ON DELETE CASCADE,
    cart_line_id bigint NOT NULL,
    status varchar(32) NOT NULL,
    unit_price_fen bigint,
    offer_version bigint,
    catalog_version bigint,
    observed_atp integer,
    amount_fen bigint NOT NULL CHECK (amount_fen >= 0),
    UNIQUE(assessment_id, cart_line_id)
);

CREATE TABLE cart_request_receipts (
    id varchar(256) PRIMARY KEY,
    buyer_id bigint NOT NULL,
    request_id varchar(128) NOT NULL,
    request_digest varchar(64) NOT NULL,
    cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    cart_version bigint NOT NULL,
    UNIQUE(buyer_id, request_id)
);

ALTER TABLE trades ADD COLUMN checkout_source_type varchar(16) NOT NULL DEFAULT 'DIRECT';
ALTER TABLE trades ADD COLUMN checkout_source_id bigint;
ALTER TABLE trades ADD COLUMN checkout_source_version bigint;
ALTER TABLE trades ADD COLUMN checkout_source_digest varchar(128) NOT NULL DEFAULT 'DIRECT';
ALTER TABLE trades ADD CONSTRAINT ck_trade_checkout_source CHECK (
    (checkout_source_type = 'DIRECT' AND checkout_source_id IS NULL AND checkout_source_version IS NULL)
    OR (checkout_source_type = 'CART' AND checkout_source_id IS NOT NULL AND checkout_source_version IS NOT NULL)
);
