SET search_path TO develop, public;

CREATE TABLE merchants (
    id              BIGINT       PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    create_time     TIMESTAMP    NOT NULL,
    update_time     TIMESTAMP    NOT NULL,
    CONSTRAINT chk_merchants_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE merchant_memberships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id     BIGINT      NOT NULL REFERENCES merchants(id),
    user_id         BIGINT      NOT NULL,
    status          VARCHAR(16) NOT NULL,
    create_time     TIMESTAMP   NOT NULL,
    update_time     TIMESTAMP   NOT NULL,
    CONSTRAINT uk_merchant_memberships_merchant_user UNIQUE (merchant_id, user_id),
    CONSTRAINT chk_merchant_memberships_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT chk_merchant_memberships_user_positive CHECK (user_id > 0)
);

CREATE INDEX idx_merchant_memberships_user_status
    ON merchant_memberships(user_id, status, merchant_id);

CREATE TABLE merchant_membership_roles (
    membership_id  BIGINT      NOT NULL REFERENCES merchant_memberships(id) ON DELETE CASCADE,
    role           VARCHAR(32) NOT NULL,
    PRIMARY KEY (membership_id, role),
    CONSTRAINT chk_merchant_membership_roles_role CHECK (
        role IN ('OWNER', 'ADMIN', 'PRODUCT_MANAGER', 'ORDER_MANAGER', 'CUSTOMER_SERVICE', 'FINANCE', 'VIEWER')
    )
);

ALTER TABLE spu
    ADD CONSTRAINT fk_spu_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE brand
    ADD CONSTRAINT fk_brand_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE product_type
    ADD CONSTRAINT fk_product_type_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE spu_snapshot
    ADD CONSTRAINT fk_spu_snapshot_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE after_sales
    ADD CONSTRAINT fk_after_sales_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE payment_orders
    ADD CONSTRAINT fk_payment_orders_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE fulfillment_orders
    ADD CONSTRAINT fk_fulfillment_orders_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id);
